// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdsuclcVVB7w5IVTT6-i8ZDKYqRMcbyY',
    appId: '1:561810984617:web:c00a3b86169035dbe0e3b8',
    messagingSenderId: '561810984617',
    projectId: 'prak10-3c283',
    authDomain: 'prak10-3c283.firebaseapp.com',
    storageBucket: 'prak10-3c283.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OVCpVbBwkjZ_pif6VCWNthqKsJ559sc',
    appId: '1:561810984617:android:7182f6dce59576d6e0e3b8',
    messagingSenderId: '561810984617',
    projectId: 'prak10-3c283',
    storageBucket: 'prak10-3c283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbz6SqIh5X-gzEJAhEH01zUB2uDpaEN7M',
    appId: '1:561810984617:ios:3e7604852f6d9cbce0e3b8',
    messagingSenderId: '561810984617',
    projectId: 'prak10-3c283',
    storageBucket: 'prak10-3c283.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbz6SqIh5X-gzEJAhEH01zUB2uDpaEN7M',
    appId: '1:561810984617:ios:3e7604852f6d9cbce0e3b8',
    messagingSenderId: '561810984617',
    projectId: 'prak10-3c283',
    storageBucket: 'prak10-3c283.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}

